spring:
  application:
    name: gateway-microservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-microservice
          uri: lb://customer-microservice
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}

server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/